### ISSUE TITLE
the issue of runing with monero wallet at the same time

### ISSUE THREAD

**Issue by netmebtc** [servc4/DeuterCoin#1]
This new version1.0.4 does not run at the same time with the monero wallet on the same computer， but version1.0.3 can run .  OS is windows10

**Comment by servc4** [comment]
Hi
I don't think that is problem with update, problem is then monero and our coin are working on same ports
18080 and 18081. Maybe i'm wrong but if you will run our wallet first then you will not be able to run monero and in different way same. In update 1.0.4 there wasn't any big changes made and port's are same in both versions.

regards
