### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by zhiyuanep** [servc4/DeuterCoin#1]
newest ubuntu 16.04.4 x64

/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/include/c++/5/thread:35:0,
                 from utilities/transactions/transaction_test.cc:9:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

**Comment by servc4** [comment]
git clone https://github.com/servc4/DeuterCoin.git
        chown user:user DeuterCoin -R
        chmod 755 DeuterCoin -R
        cd deuter
        make

**Comment by zhiyuanep** [comment]
Oh, thank you. It's my mistake.
