### ISSUE TITLE
v1.0.9 build fail

### ISSUE THREAD

**Issue by zhiyuanep** [servc4/DeuterCoin#2]
[ 99%] Building CXX object src/CMakeFiles/PaymentGateService.dir/PaymentGateService/main.cpp.o
/daemon/src/src/PaymentGateService/CoinBaseConfiguration.cpp: In constructor 'PaymentService::CoinBaseConfiguration::CoinBaseConfiguration()':
/daemon/src/src/PaymentGateService/CoinBaseConfiguration.cpp:48:24: error: 'ZAWY_DIFFICULTY_V2' is not a member of 'CryptoNote::parameters'
     ZAWY_DIFFICULTY_V2=CryptoNote::parameters::ZAWY_DIFFICULTY_V2;
                        ^
/daemon/src/src/PaymentGateService/CoinBaseConfiguration.cpp:49:46: error: 'ZAWY_DIFFICULTY_DIFFICULTY_BLOCK_VERSION' is not a member of 'CryptoNote::parameters'
     ZAWY_DIFFICULTY_DIFFICULTY_BLOCK_VERSION=CryptoNote::parameters::ZAWY_DIFFICULTY_DIFFICULTY_BLOCK_VERSION;
                                              ^
src/CMakeFiles/PaymentGateService.dir/build.make:62: recipe for target 'src/CMakeFiles/PaymentGateService.dir/PaymentGateService/CoinBaseConfiguration.cpp.o' failed

**Comment by servc4** [comment]
Hi
Can you please try now, some files hasn't been updated by GitHub desktop...

Regards
ServC4
